version: "3.7"

# Build: docker-compose -f swarm.yml build
# Up:    docker stack deploy -c swarm.yml drawsome
# Check: docker stack services drawsome
#        docker service ps drawsome_<frontend|backend|mongodb>
#        docker service logs drawsome_<frontend|backend|mongodb>
# Down:  docker stack rm drawsome

networks:
  net:

volumes:
  mongodb-data:

services:
  frontend:
    image: drawsome/frontend:latest
    build: ./client
    networks:
      - net
    ports:
      - 8080:8080
    deploy:
      replicas: 1

  backend:
    image: drawesome/backend:latest
    build: ./server
    networks:
      - net
    ports:
      - 3000:3000
    deploy:
      replicas: 1

  mongodb:
    image: mongo:4.2.3
    networks:
      - net
    volumes:
      - mongodb-data:/data/db
    deploy:
      replicas: 1
