version: "3.3"

# This was used for early local testing and development
# Actual deployment is done with manifests in /k8s

# Up:    docker stack deploy -c swarm.yml drawsome
# Check: docker stack services drawsome
#        docker service ps drawsome_<frontend|backend|mongodb>
#        docker service logs drawsome_<frontend|backend|mongodb>
# Down:  docker stack rm drawsome

networks:
  net:

volumes:
  mongodb-data:

services:
  frontend:
    image: alexanderursu99/drawsome-frontend:latest
    networks:
      - net
    ports:
      - 80:80
    deploy:
      replicas: 1

  backend:
    image: alexanderursu99/drawsome-backend:latest
    networks:
      - net
    ports:
      - 3000:3000
    environment:
      SESSION_SECRET: ${SESSION_SECRET:?no_session_secret}
    deploy:
      replicas: 1

  mongodb:
    image: mongo:4.2.3
    networks:
      - net
    volumes:
      - mongodb-data:/data/db
    deploy:
      replicas: 1
