apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
      - image: alexanderursu99/drawsome-backend:67
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SESSION_SECRET

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: backend
  type: NodePort
